spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifetime: 150000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true

JWT_SECRET_KEY: {{JWT_SECRET_KEY}}
JWT_TIME_EXPIRATION: {{JWT_TIME_EXPIRATION}}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: TRACE

server:
  port: 8080
